# Generated by Django 5.2.17 on 2026-09-30 12:03

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Bu nomdagi foydalanuvchi allaqachon mavjud.'}, help_text="Majburiy. 150 ta yoki undan kam belgilar. Harflar, raqamlar, probel (bo'sh joy) va @/./+/-/_ belgilariga ruxsat beriladi.", max_length=150, unique=True, validators=[apps.accounts.models.SpaceAllowedUsernameValidator()], verbose_name='Foydalanuvchi nomi'),
        ),
    ]
