# Generated by Django 5.2.17 on 2026-10-05 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='Foydalanuvchi nomi')),
                ('user_full_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Foydalanuvchi F.I.SH')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP manzil')),
                ('mac_address', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='MAC ID / Qurilma ID')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('action', models.CharField(choices=[('create', 'Yaratish'), ('update', 'Tahrirlash'), ('delete', "O'chirish")], db_index=True, max_length=20, verbose_name='Harakat turi')),
                ('app_label', models.CharField(db_index=True, max_length=100, verbose_name='Ilova (App)')),
                ('model_name', models.CharField(db_index=True, max_length=100, verbose_name='Model nomi')),
                ('object_id', models.CharField(db_index=True, max_length=255, verbose_name='Obyekt ID')),
                ('object_repr', models.CharField(blank=True, default='', max_length=500, verbose_name='Obyekt qisqa matni')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name="O'zgarishlar (Diff: eski va yangi)")),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='Eski qiymatlar')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='Yangi qiymatlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Qayd etilgan vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit loglari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='common_audi_model_n_d26c0d_idx'), models.Index(fields=['user', 'created_at'], name='common_audi_user_id_8b57b8_idx'), models.Index(fields=['action', 'created_at'], name='common_audi_action_f07e2b_idx'), models.Index(fields=['ip_address', 'created_at'], name='common_audi_ip_addr_736214_idx'), models.Index(fields=['mac_address', 'created_at'], name='common_audi_mac_add_bbd7da_idx')],
            },
        ),
    ]
