# Generated by Django 5.2.17 on 2026-09-29 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrillingRigType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Uskuna turi nomi')),
            ],
            options={
                'verbose_name': "Burg'ulash uskunasi turi",
                'verbose_name_plural': "Burg'ulash uskunasi turlari",
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Korxona nomi')),
            ],
            options={
                'verbose_name': 'Korxona',
                'verbose_name_plural': 'Korxonalar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Foreman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='F.I.SH')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon raqami')),
            ],
            options={
                'verbose_name': 'Usta (Foreman)',
                'verbose_name_plural': 'Ustalar (Foremen)',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Lavozim nomi')),
            ],
            options={
                'verbose_name': 'Lavozim',
                'verbose_name_plural': 'Lavozimlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Hudud nomi')),
            ],
            options={
                'verbose_name': 'Hudud',
                'verbose_name_plural': 'Hududlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Transport turi nomi')),
            ],
            options={
                'verbose_name': 'Transport turi',
                'verbose_name_plural': 'Transport turlari',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Xodim F.I.SH')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon raqami')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='directory.position', verbose_name='Lavozimi')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['position', 'name'], name='directory_e_positio_7f09b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Maydon nomi')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='directory.region', verbose_name='Tegishli hudud')),
            ],
            options={
                'verbose_name': 'Maydon',
                'verbose_name_plural': 'Maydonlar',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['region', 'name'], name='directory_a_region__642522_idx')],
            },
        ),
    ]
