# Generated by Django 5.2.17 on 2026-10-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepthsLayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Qatlam nomi')),
            ],
            options={
                'verbose_name': 'Chuqurlik qatlami',
                'verbose_name_plural': 'Chuqurlik qatlamlari',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Mashina turi nomi')),
            ],
            options={
                'verbose_name': 'Mashina turi',
                'verbose_name_plural': 'Mashina turlari',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Resurs nomi')),
            ],
            options={
                'verbose_name': 'Resurs',
                'verbose_name_plural': 'Resurslar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name="O'lchov birligi nomi")),
            ],
            options={
                'verbose_name': "O'lchov birligi",
                'verbose_name_plural': "O'lchov birliklari",
                'ordering': ['-id'],
            },
        ),
    ]
