# Generated by Django 5.2.17 on 2026-09-29 09:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('description', models.TextField(verbose_name='Kunlik ish tavsifi')),
            ],
            options={
                'verbose_name': 'Kunlik ish hisoboti',
                'verbose_name_plural': 'Kunlik ish hisobotlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyTransportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Transport vositalari soni')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Transport bo'yicha izoh")),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_transport_items', to='directory.transporttype', verbose_name='Transport turi')),
                ('daily_work_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_items', to='operations.dailyworkdescription', verbose_name='Kunlik ish hisoboti')),
            ],
            options={
                'verbose_name': 'Kunlik transport vositasi',
                'verbose_name_plural': 'Kunlik transport vositalari',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DerrickErectionOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('from_well_number', models.CharField(max_length=50, verbose_name='Qaysi quduqdan (№)')),
                ('to_well_number', models.CharField(max_length=50, verbose_name='Qaysi quduqqa (№)')),
                ('number_employees', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ishchilar soni')),
                ('distance_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Masofa (km)')),
                ('plan_days', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rejadagi kunlar')),
                ('expected_drilling_date', models.DateField(blank=True, null=True, verbose_name="Kutilayotgan burg'ulash boshlanish sanasi")),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Bajarilish foizi (%)')),
                ('delay_reason', models.TextField(blank=True, null=True, verbose_name='Kechikish sababi')),
                ('work_description', models.TextField(blank=True, null=True, verbose_name='Bajarilayotgan ish tavsifi')),
                ('drilling_rig_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='directory.drillingrigtype', verbose_name="Burg'ulash uskunasi turi")),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='directory.enterprise', verbose_name='Korxona')),
                ('foreman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='directory.foreman', verbose_name='Usta (Prorab)')),
                ('from_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations_from', to='directory.area', verbose_name='Qaysi maydondan')),
                ('to_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations_to', to='directory.area', verbose_name='Qaysi maydonga')),
            ],
            options={
                'verbose_name': 'VBM Operatsiyasi',
                'verbose_name_plural': 'VBM Operatsiyalari',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='dailyworkdescription',
            name='derrick_erection_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_works', to='operations.derrickerectionoperation', verbose_name='VBM Operatsiyasi'),
        ),
        migrations.CreateModel(
            name='OperationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('stage_type', models.CharField(choices=[('dismantling', 'Demontaj'), ('transportation', 'Tashish'), ('installation', 'Montaj')], max_length=50, verbose_name='Bosqich turi')),
                ('plan_days', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reja kun')),
                ('fact_days', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fakt kun')),
                ('plan_start_date', models.DateField(blank=True, null=True, verbose_name='Rejadagi boshlanish sanasi')),
                ('plan_end_date', models.DateField(blank=True, null=True, verbose_name='Rejadagi tugash sanasi')),
                ('fact_start_date', models.DateField(blank=True, null=True, verbose_name='Amaldagi boshlanish sanasi')),
                ('fact_end_date', models.DateField(blank=True, null=True, verbose_name='Amaldagi tugash sanasi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh / Tavsif')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='operations.derrickerectionoperation', verbose_name='Operatsiya')),
            ],
            options={
                'verbose_name': 'Operatsiya bosqichi',
                'verbose_name_plural': 'Operatsiya bosqichlari',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='derrickerectionoperation',
            index=models.Index(fields=['enterprise', 'foreman'], name='operations__enterpr_8fe74a_idx'),
        ),
        migrations.AddIndex(
            model_name='derrickerectionoperation',
            index=models.Index(fields=['from_area', 'to_area'], name='operations__from_ar_dc2f58_idx'),
        ),
        migrations.AddIndex(
            model_name='derrickerectionoperation',
            index=models.Index(fields=['completion_percentage'], name='operations__complet_26cb8f_idx'),
        ),
        migrations.AddIndex(
            model_name='operationstage',
            index=models.Index(fields=['operation', 'stage_type'], name='operations__operati_7be71f_idx'),
        ),
    ]
