# Generated by Django 5.2.17 on 2026-10-05 04:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_depthslayers_machinetype_resources_unit'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillingBPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('number', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='BPA / Shartnoma raqami')),
                ('well_number', models.CharField(db_index=True, max_length=50, verbose_name='Quduq raqami (№)')),
                ('drilling_start_date', models.DateTimeField(blank=True, null=True, verbose_name="Burg'ulash boshlanish vaqti")),
                ('depth_plan', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rejadagi umumiy chuqurlik (m)')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drilling_bpas', to='directory.area', verbose_name='Maydon / Kon')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drilling_bpas', to='directory.employee', verbose_name="Mas'ul xodim")),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drilling_bpas', to='directory.enterprise', verbose_name='Korxona')),
                ('machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drilling_bpas', to='directory.machinetype', verbose_name='Mashina / Mexanizm turi')),
            ],
            options={
                'verbose_name': "Burg'ulash (BPA) operatsiyasi",
                'verbose_name_plural': "Burg'ulash (BPA) operatsiyalari",
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DepthsLayersLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('length', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Qatlam qalinligi / chuqurligi (m)')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depths_layers_lengths', to='directory.depthslayers', verbose_name='Chuqurlik qatlami')),
                ('drilling_bpa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depths_layers_lengths', to='operations.drillingbpa', verbose_name="Burg'ulash BPA")),
            ],
            options={
                'verbose_name': "Chuqurlik qatlami oralig'i",
                'verbose_name_plural': 'Chuqurlik qatlamlari oraliqlari',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DailyWorkDescriptionBPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('report_date', models.DateField(db_index=True, verbose_name='Hisobot sanasi')),
                ('description', models.TextField(blank=True, default='', verbose_name='Bajarilgan ishlar tavsifi')),
                ('density', models.FloatField(default=0.0, verbose_name='Eritma zichligi (g/sm³)')),
                ('viscosity', models.FloatField(default=0.0, verbose_name='Qovushqoqlik (sek)')),
                ('fluid_loss', models.FloatField(default=0.0, verbose_name='Suv beruvchanlik (sm³/30daq)')),
                ('mud_cake', models.FloatField(default=0.0, verbose_name="Gil po'stlog'i (mm)")),
                ('ph_level', models.FloatField(default=0.0, verbose_name='pH darajasi')),
                ('weight_on_bit', models.FloatField(default=0.0, verbose_name='Dolotoga tushadigan yuk (tonna)')),
                ('rpm', models.FloatField(default=0.0, verbose_name='Rotor tezligi (ayl/daq)')),
                ('pump_pressure', models.FloatField(default=0.0, verbose_name='Nasos bosimi (MPa / bar)')),
                ('flow_rate', models.FloatField(default=0.0, verbose_name='Eritma sarfi (l/sek)')),
                ('drilling_bpa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_works', to='operations.drillingbpa', verbose_name="Burg'ulash BPA")),
            ],
            options={
                'verbose_name': 'BPA kunlik ish hisoboti',
                'verbose_name_plural': 'BPA kunlik ish hisobotlari',
                'ordering': ['-report_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AvailableResourcesBPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('value', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Miqdori / Qiymati')),
                ('description', models.TextField(blank=True, default='', verbose_name='Izoh / Tavsif')),
                ('resources', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='available_in_bpas', to='directory.resources', verbose_name='Resurs')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='available_in_bpas', to='directory.unit', verbose_name="O'lchov birligi")),
                ('drilling_bpa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_resources', to='operations.drillingbpa', verbose_name="Burg'ulash BPA")),
            ],
            options={
                'verbose_name': 'BPA mavjud resursi',
                'verbose_name_plural': 'BPA mavjud resurslari',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WellDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('type', models.CharField(choices=[('plan', 'Reja'), ('fact', 'Fakt')], default='plan', max_length=10, verbose_name='Turi (Reja/Fakt)')),
                ('pipe_diameter', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Quvur diametri (mm)')),
                ('length', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Uzunligi / Chuqurligi (m)')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish sanasi va vaqti')),
                ('drilling_bpa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='well_designs', to='operations.drillingbpa', verbose_name="Burg'ulash BPA")),
            ],
            options={
                'verbose_name': 'Quduq konstruksiyasi',
                'verbose_name_plural': 'Quduq konstruksiyalari',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WellDesignInLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
                ('type', models.CharField(choices=[('day', 'Kunlik'), ('month', 'Oylik'), ('year', 'Yillik')], default='day', max_length=10, verbose_name='Davr turi (kun/oy/yil)')),
                ('length_plan', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name="Reja bo'yicha uzunlik (m)")),
                ('length_fact', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name="Fakt bo'yicha uzunlik (m)")),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish sanasi va vaqti')),
                ('drilling_bpa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='well_designs_in_length', to='operations.drillingbpa', verbose_name="Burg'ulash BPA")),
            ],
            options={
                'verbose_name': "Quduq o'tish dinamikasi (uzunlik bo'yicha)",
                'verbose_name_plural': "Quduq o'tish dinamikasi (uzunlik bo'yicha)",
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='drillingbpa',
            index=models.Index(fields=['enterprise', 'well_number'], name='operations__enterpr_1b109c_idx'),
        ),
        migrations.AddIndex(
            model_name='drillingbpa',
            index=models.Index(fields=['area', 'well_number'], name='operations__area_id_e1e553_idx'),
        ),
        migrations.AddIndex(
            model_name='depthslayerslength',
            index=models.Index(fields=['drilling_bpa', 'layer'], name='operations__drillin_299c73_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyworkdescriptionbpa',
            index=models.Index(fields=['drilling_bpa', 'report_date'], name='operations__drillin_d35cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='availableresourcesbpa',
            index=models.Index(fields=['drilling_bpa', 'resources'], name='operations__drillin_39b3c2_idx'),
        ),
        migrations.AddIndex(
            model_name='welldesign',
            index=models.Index(fields=['drilling_bpa', 'type'], name='operations__drillin_4e213b_idx'),
        ),
        migrations.AddIndex(
            model_name='welldesigninlength',
            index=models.Index(fields=['drilling_bpa', 'type'], name='operations__drillin_d466a8_idx'),
        ),
    ]
